const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Physics,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.solid,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Plugins.video,
		C3.Plugins.sliderbar,
		C3.Plugins.Button,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Behaviors.Fade,
		C3.Behaviors.Timer,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.CompareKey,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{btnNewGameMenu: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Physics: 0},
	{peixeBolaGatoFeliz: 0},
	{ExploradorDeRotas: 0},
	{cachorroAgiota: 0},
	{Solid: 0},
	{bumper: 0},
	{grama: 0},
	{areia: 0},
	{agua: 0},
	{buraco: 0},
	{catSpawner: 0},
	{mira: 0},
	{Touch: 0},
	{PontoDeControle: 0},
	{DebugText: 0},
	{Audio: 0},
	{optionsBlock: 0},
	{buracoBandeira: 0},
	{jumpscare: 0},
	{tacadasText: 0},
	{pontosText: 0},
	{MosaicoGame: 0},
	{textHud: 0},
	{hudBar: 0},
	{stage1: 0},
	{catPoints: 0},
	{catMoviment: 0},
	{tutorialText: 0},
	{mainMenu: 0},
	{tableResults: 0},
	{stageResultsText: 0},
	{tacadasEfStageText: 0},
	{moedasAdqStageText: 0},
	{conclusionBonusText: 0},
	{pontosAdqText: 0},
	{calcPontuacaoText: 0},
	{ranqueText: 0},
	{continueButton: 0},
	{resetButton: 0},
	{btnContinueMenu: 0},
	{btnEscolhaFases: 0},
	{mainMenuNewGameTxt: 0},
	{gatoOptions: 0},
	{cachorroOptions: 0},
	{barraDeslizanteMusica: 0},
	{optionsMenuText: 0},
	{screenIcon: 0},
	{screenOptionButton: 0},
	{barraDeslizanteEfeitosSonoros: 0},
	{musicOptionText: 0},
	{soundEffectOptionText: 0},
	{screenOptionText: 0},
	{screenOptionText2: 0},
	{backOptionButton: 0},
	{ArmazenamentoLocal: 0},
	{mainMenuContinueTxt: 0},
	{Navegador: 0},
	{AJAX: 0},
	{ArraySave: 0},
	{btnTest: 0},
	{stage2: 0},
	{primeiraVez: 0},
	{cameraPerigosa: 0},
	{Esmaecer: 0},
	{flashCameraSprite: 0},
	{picture: 0},
	{miauMal: 0},
	{miaUau: 0},
	{miaucrivel: 0},
	{rankCatSpawner: 0},
	{savingGameIcon: 0},
	{savingGameSpawner: 0},
	{Cronômetro: 0},
	{cachorroAgiotaSpawner: 0},
	{continuePassButton: 0},
	{finalBlock: 0},
	{textTitleStageSelection: 0},
	{inputFaseEscolhida: 0},
	{confirmarFaseTxt: 0},
	{btnConfirmarFase: 0},
	{mainMenuEscolhaFasesTxt: 0},
	{typeNumberTxt: 0},
	{stageFinal: 0},
	{fishBallCat: 0},
	{Sólido: 0},
	{Física: 0},
	{crazySkeleton: 0},
	{stage3: 0},
	{stage4: 0},
	{stage5: 0},
	{cameraPrimeiraVez: 0},
	{tacadasResultadoFase: 0},
	{pontos: 0},
	{pontosResultadoFase: 0},
	{moedasColetadasFase: 0},
	{lancamentoAngulo: 0},
	{maxForça: 0},
	{força: 0},
	{jumpscareAtivo: 0},
	{terminouFase: 0},
	{numeroFaseAtual: 0},
	{menuEscolhaFasesLiberado: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	btnNewGameMenu: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	peixeBolaGatoFeliz: class extends self.ISpriteInstance {},
	cachorroAgiota: class extends self.ISpriteInstance {},
	bumper: class extends self.ISpriteInstance {},
	grama: class extends self.ISpriteInstance {},
	areia: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	buraco: class extends self.ISpriteInstance {},
	catSpawner: class extends self.ISpriteInstance {},
	mira: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	PontoDeControle: class extends self.ISpriteInstance {},
	DebugText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	optionsBlock: class extends self.ISpriteInstance {},
	buracoBandeira: class extends self.ISpriteInstance {},
	jumpscare: class extends self.ISpriteInstance {},
	tacadasText: class extends self.ITextInstance {},
	pontosText: class extends self.ITextInstance {},
	MosaicoGame: class extends self.ITilemapInstance {},
	textHud: class extends self.ISpriteInstance {},
	hudBar: class extends self.ISpriteInstance {},
	stage1: class extends self.ISpriteInstance {},
	catPoints: class extends self.ISpriteInstance {},
	catMoviment: class extends self.IWorldInstance {},
	tutorialText: class extends self.ITextInstance {},
	mainMenu: class extends self.ISpriteInstance {},
	tableResults: class extends self.ISpriteInstance {},
	stageResultsText: class extends self.ITextInstance {},
	tacadasEfStageText: class extends self.ITextInstance {},
	moedasAdqStageText: class extends self.ITextInstance {},
	conclusionBonusText: class extends self.ITextInstance {},
	pontosAdqText: class extends self.ITextInstance {},
	calcPontuacaoText: class extends self.ITextInstance {},
	ranqueText: class extends self.ITextInstance {},
	continueButton: class extends self.ISpriteInstance {},
	resetButton: class extends self.ISpriteInstance {},
	btnContinueMenu: class extends self.ISpriteInstance {},
	btnEscolhaFases: class extends self.ISpriteInstance {},
	mainMenuNewGameTxt: class extends self.ITextInstance {},
	gatoOptions: class extends self.ISpriteInstance {},
	cachorroOptions: class extends self.ISpriteInstance {},
	barraDeslizanteMusica: class extends self.ISliderBarInstance {},
	optionsMenuText: class extends self.ITextInstance {},
	screenIcon: class extends self.ISpriteInstance {},
	screenOptionButton: class extends self.IButtonInstance {},
	barraDeslizanteEfeitosSonoros: class extends self.ISliderBarInstance {},
	musicOptionText: class extends self.ITextInstance {},
	soundEffectOptionText: class extends self.ITextInstance {},
	screenOptionText: class extends self.ITextInstance {},
	screenOptionText2: class extends self.ITextInstance {},
	backOptionButton: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	mainMenuContinueTxt: class extends self.ITextInstance {},
	Navegador: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	ArraySave: class extends self.IArrayInstance {},
	btnTest: class extends self.ISpriteInstance {},
	stage2: class extends self.ISpriteInstance {},
	cameraPerigosa: class extends self.ISpriteInstance {},
	flashCameraSprite: class extends self.ISpriteInstance {},
	picture: class extends self.ISpriteInstance {},
	miauMal: class extends self.ISpriteInstance {},
	miaUau: class extends self.ISpriteInstance {},
	miaucrivel: class extends self.ISpriteInstance {},
	rankCatSpawner: class extends self.ISpriteInstance {},
	savingGameIcon: class extends self.ISpriteInstance {},
	savingGameSpawner: class extends self.ISpriteInstance {},
	cachorroAgiotaSpawner: class extends self.ISpriteInstance {},
	continuePassButton: class extends self.ISpriteInstance {},
	finalBlock: class extends self.ISpriteInstance {},
	textTitleStageSelection: class extends self.ITextInstance {},
	inputFaseEscolhida: class extends self.ITextInputInstance {},
	confirmarFaseTxt: class extends self.ITextInstance {},
	btnConfirmarFase: class extends self.ISpriteInstance {},
	mainMenuEscolhaFasesTxt: class extends self.ITextInstance {},
	typeNumberTxt: class extends self.ITextInstance {},
	stageFinal: class extends self.ISpriteInstance {},
	fishBallCat: class extends self.ISpriteInstance {},
	crazySkeleton: class extends self.ISpriteInstance {},
	stage3: class extends self.ISpriteInstance {},
	stage4: class extends self.ISpriteInstance {},
	stage5: class extends self.ISpriteInstance {}
}